In [3]:
import numpy as np

R = np.array([
    [5,4,0],
    [4,0,1]
], dtype=float)
# R is actual observations

U = np.array([
    [0.5,0.3],
    [0.4,0.7]
], dtype=float)

# U is hidden features from users we are gonna update them; use them as parameters

V = np.array([
    [0.6,0.2],
    [0.8,0.1],
    [0.2,0.9]
])

# V is hidden features from movie (sci-fi, romantic) we are gonna use this as parameters as well

In [5]:
predictions = U @ V.T
print(f"Actual ratings {R}")

print(f"\nPredictions: {predictions}")

Actual ratings [[5. 4. 0.]
 [4. 0. 1.]]

Predictions: [[0.36 0.43 0.37]
 [0.38 0.39 0.71]]


In [6]:
mask = R != 0

print(mask)

[[ True  True False]
 [ True False  True]]


In [7]:
errors = R[mask] - predictions[mask]
print(errors)

[4.64 3.57 3.62 0.29]


In [8]:
mse = np.mean(errors ** 2)

print("MSE :", mse)

MSE : 11.865749999999998


In [9]:
actual = R[0, 0]      # 5
prediction = predictions[0, 0]  # 0.36
error = actual - prediction

In [10]:
user_vec = U[0].copy()
movie_vec = V[0].copy()

print(user_vec,movie_vec)

[0.5 0.3] [0.6 0.2]


In [11]:
lr = 0.01

In [12]:
U[0]+= lr * error * movie_vec
V[0]+= lr * error * user_vec

new_predictions = U[0] @ V[0]

print(f"Old prediction: {prediction}\nNew prediction: {new_predictions}")

Old prediction: 0.36
New prediction: 0.3951110656


In [13]:
epoch = 1000

for epochs in range(epoch):
    for u in range(R.shape[0]): # Users
        for i in range(R.shape[1]): #Movies
            if R[u,i] == 0:
                continue
            prediction = U[u] @ V[i]
            error = R[u,i] - prediction

            user_vec = U[u].copy()

            U[u] += lr*error*V[i]
            V[i] += lr*error*user_vec
        

In [14]:
predictions = U @ V.T

print(f"Actual ratings: {R}\nPredicted Ratings: {predictions}")

Actual ratings: [[5. 4. 0.]
 [4. 0. 1.]]
Predicted Ratings: [[5.         4.         0.82197072]
 [4.         2.93410739 1.        ]]


In [16]:
mask = R != 0

errors = R[mask] - predictions[mask]
mse = np.mean(errors ** 2)

print("\nFinal MSE:", mse)


Final MSE: 1.124619828005705e-28


In [17]:
# Train / Test Evaluation

In [31]:
R = np.array([
    [5, 4, 0],
    [4, 0, 1]
], dtype=float)

R_train = R.copy()

test_user = 0
test_movie = 1

# gerçek değeri ÖNCE R'den al
test_actual = R[test_user, test_movie]

# sonra sadece train copy'de gizle
R_train[test_user, test_movie] = 0

print("R:")
print(R)

print("\nR_train:")
print(R_train)

print("\ntest_actual:", test_actual)

R:
[[5. 4. 0.]
 [4. 0. 1.]]

R_train:
[[5. 0. 0.]
 [4. 0. 1.]]

test_actual: 4.0


In [32]:
U = np.array([
    [0.5, 0.3],
    [0.4, 0.7]
], dtype=float)

V = np.array([
    [0.6, 0.2],
    [0.8, 0.1],
    [0.2, 0.9]
], dtype=float)

In [33]:
lr = 0.01
epochs = 1000

for epoch in range(epochs):

    for u in range(R_train.shape[0]):
        for i in range(R_train.shape[1]):

            if R_train[u, i] == 0:
                continue

            prediction = U[u] @ V[i]
            error = R_train[u, i] - prediction

            user_vec = U[u].copy()
            movie_vec = V[i].copy()

            U[u] += lr * error * movie_vec
            V[i] += lr * error * user_vec

In [34]:
test_prediction = U[test_user] @ V[test_movie]

print("Actual rating:", test_actual)
print("Predicted rating:", test_prediction)
print("Absolute error:", abs(test_actual - test_prediction))

Actual rating: 4.0
Predicted rating: 1.4818260683324591
Absolute error: 2.518173931667541


In [35]:
# Time to work with clean and bigger dataset

In [36]:
R = np.array([
    [5, 4, 1, 0, 0, 3],
    [5, 4, 2, 5, 4, 0],
    [1, 2, 5, 1, 0, 4],
    [4, 5, 1, 4, 5, 0],
    [0, 4, 2, 5, 4, 3],
    [2, 1, 5, 0, 1, 4]
], dtype=float)

num_users = R.shape[0]
num_movies = R.shape[1]
num_features = 3

np.random.seed(42)

U = np.random.rand(num_users, num_features)
V = np.random.rand(num_movies, num_features)

print("R shape:", R.shape)
print("U shape:", U.shape)
print("V shape:", V.shape)

print("\nU:")
print(U)

print("\nV:")
print(V)

R shape: (6, 6)
U shape: (6, 3)
V shape: (6, 3)

U:
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643]]

V:
[[0.43194502 0.29122914 0.61185289]
 [0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378]
 [0.51423444 0.59241457 0.04645041]
 [0.60754485 0.17052412 0.06505159]
 [0.94888554 0.96563203 0.80839735]]


In [37]:
R_train = R.copy()

test_cases = [
    (0, 1),  # User 0, Movie 1
    (1, 3),  # User 1, Movie 3
    (2, 2),  # User 2, Movie 2
    (3, 4)   # User 3, Movie 4
]

test_actuals = []

for u, i in test_cases:
    test_actuals.append(R[u, i])
    R_train[u, i] = 0

print("R_train:")
print(R_train)

print("\nHidden test ratings:")
print(test_actuals)

R_train:
[[5. 0. 1. 0. 0. 3.]
 [5. 4. 2. 0. 4. 0.]
 [1. 2. 0. 1. 0. 4.]
 [4. 5. 1. 4. 0. 0.]
 [0. 4. 2. 5. 4. 3.]
 [2. 1. 5. 0. 1. 4.]]

Hidden test ratings:
[np.float64(4.0), np.float64(5.0), np.float64(5.0), np.float64(5.0)]


In [38]:
# Reinitalizing U and V for training

In [39]:
np.random.seed(42)

U = np.random.rand(num_users, num_features)
V = np.random.rand(num_movies, num_features)

In [40]:
lr = 0.01
epochs = 1000

for epoch in range(epochs):

    for u in range(R_train.shape[0]):
        for i in range(R_train.shape[1]):

            if R_train[u, i] == 0:
                continue

            prediction = U[u] @ V[i]
            error = R_train[u, i] - prediction

            user_vec = U[u].copy()
            movie_vec = V[i].copy()

            U[u] += lr * error * movie_vec
            V[i] += lr * error * user_vec

In [41]:
test_predictions = []

for u, i in test_cases:
    predicted = U[u] @ V[i]
    test_predictions.append(predicted)

    print(
        f"User {u}, Movie {i} | "
        f"Actual: {R[u, i]:.2f} | "
        f"Predicted: {predicted:.2f}"
    )

User 0, Movie 1 | Actual: 4.00 | Predicted: 5.55
User 1, Movie 3 | Actual: 5.00 | Predicted: 5.00
User 2, Movie 2 | Actual: 5.00 | Predicted: 4.24
User 3, Movie 4 | Actual: 5.00 | Predicted: 3.03


In [42]:
test_actuals = np.array(test_actuals)
test_predictions = np.array(test_predictions)

rmse = np.sqrt(
    np.mean(
        (test_actuals - test_predictions) ** 2
    )
)

print("\nTest RMSE:", rmse)


Test RMSE: 1.3108514793722807


In [43]:
# Adding L2 regularization error

In [44]:
lr = 0.01
epochs = 1000
reg = 0.02

for epoch in range(epochs):

    for u in range(R_train.shape[0]):
        for i in range(R_train.shape[1]):

            if R_train[u, i] == 0:
                continue

            prediction = U[u] @ V[i]
            error = R_train[u, i] - prediction

            user_vec = U[u].copy()
            movie_vec = V[i].copy()

            U[u] += lr * (
                error * movie_vec
                - reg * user_vec
            )

            V[i] += lr * (
                error * user_vec
                - reg * movie_vec
            )

In [46]:
test_predictions = []

for u, i in test_cases:
    predicted = U[u] @ V[i]
    test_predictions.append(predicted)

    print(
        f"User {u}, Movie {i} | "
        f"Actual: {R[u, i]:.2f} | "
        f"Predicted: {predicted:.2f}"
    )

User 0, Movie 1 | Actual: 4.00 | Predicted: 4.90
User 1, Movie 3 | Actual: 5.00 | Predicted: 4.95
User 2, Movie 2 | Actual: 5.00 | Predicted: 3.35
User 3, Movie 4 | Actual: 5.00 | Predicted: 3.17


In [47]:
test_actuals = np.array(test_actuals)
test_predictions = np.array(test_predictions)

rmse = np.sqrt(
    np.mean(
        (test_actuals - test_predictions) ** 2
    )
)

print("Regularized Test RMSE:", rmse)

Regularized Test RMSE: 1.3094774274709786


In [48]:
known_ratings = R_train[R_train != 0]

mu = np.mean(known_ratings)

user_bias = np.zeros(num_users)
movie_bias = np.zeros(num_movies)

np.random.seed(42)

U = np.random.rand(num_users, num_features)
V = np.random.rand(num_movies, num_features)

print("Global mean:", mu)

Global mean: 3.08


In [49]:
lr = 0.01
epochs = 1000
reg = 0.02

for epoch in range(epochs):

    for u in range(R_train.shape[0]):
        for i in range(R_train.shape[1]):

            if R_train[u, i] == 0:
                continue

            prediction = (
                mu
                + user_bias[u]
                + movie_bias[i]
                + U[u] @ V[i]
            )

            error = R_train[u, i] - prediction

            user_vec = U[u].copy()
            movie_vec = V[i].copy()

            # update biases
            user_bias[u] += lr * (
                error - reg * user_bias[u]
            )

            movie_bias[i] += lr * (
                error - reg * movie_bias[i]
            )

            # update latent factors
            U[u] += lr * (
                error * movie_vec
                - reg * user_vec
            )

            V[i] += lr * (
                error * user_vec
                - reg * movie_vec
            )

In [50]:
test_predictions = []

for u, i in test_cases:

    predicted = (
        mu
        + user_bias[u]
        + movie_bias[i]
        + U[u] @ V[i]
    )

    predicted = np.clip(predicted, 1, 5)

    test_predictions.append(predicted)

    print(
        f"User {u}, Movie {i} | "
        f"Actual: {R[u, i]:.2f} | "
        f"Predicted: {predicted:.2f}"
    )

User 0, Movie 1 | Actual: 4.00 | Predicted: 4.65
User 1, Movie 3 | Actual: 5.00 | Predicted: 5.00
User 2, Movie 2 | Actual: 5.00 | Predicted: 3.74
User 3, Movie 4 | Actual: 5.00 | Predicted: 3.73


In [51]:
test_predictions = np.array(test_predictions)

rmse = np.sqrt(
    np.mean(
        (test_actuals - test_predictions) ** 2
    )
)

print("\nBias + Regularization Test RMSE:", rmse)


Bias + Regularization Test RMSE: 0.9520230714857649


In [52]:
results = []

for num_features in [2, 3, 4]:
    for reg in [0.001, 0.01, 0.02, 0.05]:

        np.random.seed(42)

        U = np.random.rand(num_users, num_features)
        V = np.random.rand(num_movies, num_features)

        user_bias = np.zeros(num_users)
        movie_bias = np.zeros(num_movies)

        mu = np.mean(R_train[R_train != 0])

        lr = 0.01
        epochs = 1000

        for epoch in range(epochs):

            for u in range(R_train.shape[0]):
                for i in range(R_train.shape[1]):

                    if R_train[u, i] == 0:
                        continue

                    prediction = (
                        mu
                        + user_bias[u]
                        + movie_bias[i]
                        + U[u] @ V[i]
                    )

                    error = R_train[u, i] - prediction

                    user_vec = U[u].copy()
                    movie_vec = V[i].copy()

                    user_bias[u] += lr * (
                        error - reg * user_bias[u]
                    )

                    movie_bias[i] += lr * (
                        error - reg * movie_bias[i]
                    )

                    U[u] += lr * (
                        error * movie_vec
                        - reg * user_vec
                    )

                    V[i] += lr * (
                        error * user_vec
                        - reg * movie_vec
                    )

        preds = []

        for u, i in test_cases:
            pred = (
                mu
                + user_bias[u]
                + movie_bias[i]
                + U[u] @ V[i]
            )

            pred = np.clip(pred, 1, 5)
            preds.append(pred)

        preds = np.array(preds)

        rmse = np.sqrt(
            np.mean((test_actuals - preds) ** 2)
        )

        results.append(
            (num_features, reg, rmse)
        )

In [53]:
results = sorted(
    results,
    key=lambda x: x[2]
)

for result in results:
    print(result)

(2, 0.02, np.float64(0.803230601409525))
(2, 0.05, np.float64(0.8081195826767712))
(2, 0.01, np.float64(0.8180519597517891))
(2, 0.001, np.float64(0.843173401833268))
(3, 0.05, np.float64(0.8857005313955617))
(4, 0.05, np.float64(0.9504237069196562))
(3, 0.02, np.float64(0.9520230714857649))
(3, 0.01, np.float64(1.0049196830704674))
(3, 0.001, np.float64(1.075283036305594))
(4, 0.02, np.float64(1.3345793842896299))
(4, 0.01, np.float64(1.6363921404667818))
(4, 0.001, np.float64(2.0239526658635345))
